POST http://localhost:4000/api/users/signup
Content-Type:Content-Type

{
    "fullName":"sammil",
    "email":"sami@yialem.com",
  "phoneNumber":"+251933324767",
    "password":"samisami"
}

### 
GET http://localhost:4000/api/users
###
DELETE http://localhost:4000/api/users/61fd3dc3d3442a06c8c2dcb0
###
POST http://localhost:4000/api/auth 
Content-Type: : application/json

{
    "email":  "yihalem@yihalem.com",
    "password":"yihalem123"
}
###
GET http://localhost:4000/api/doctors
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWZkNDM5Zjk2YjczNGM3MjUwOTQ4MWIiLCJpYXQiOjE2NDM5OTI3MjB9.sxIloibryCVZ6HRHGpqPjw447KpJ27kupyKvckFikZo

###
POST http://localhost:4000/api/doctors
Content-Type: : application/json


{
  "fullName":"Dr. Darren Elder",
  "email":"darren@gmail.com",
  "phoneNumber":"+251933324728",
  "password":"darrenelder",
  "currentWork":"Amin General Hospital",
  "category":"Dentist",
  "about":"i AM DARREN. i AM PROFICIENT DENTIST WITH EXPEREINCE OF MORETHAN 5 YEARS ON TOOTH SPECIALITY. IO WOULD CONSULT YOU WELL ON.",
  "education":["BAHIRDAR UNIVRSITY GENERAL MEDICINE"],
  "experience":["Glowing Smiles Family Dental Clinic,2010 - Present (5 years)","Dream Smile Dental Practice, 2005 - 2007 (2 years)"],
  "certifications":["Humanitarian Award"],
  "services":["Tooth cleaning","Root Canal Therapy","Implants","Surgical Extractions"],
  "location":"Addis Ababa,Bole,wollo Sefer",
  "businessHours":["2:00-4:00","8:00-0:00"],
  "Pricing":"300Birr"
}